env: dev

server:
  port: 8888

security:
  jwt:
    secretKey: niko
  ignoreUris:
    - "/api/login"
    - "/api/register"

mysql:
  username: "root"
  password: "root123456"
  database: "gin"

zap:
  maxSize: 1
  maxBackups: 10
  maxAge: 90


