env: test

server:
  port: 8888

security:
  jwt:
    secretKey: niko
  ignoreUris:
    - "/api/v1/login"
    - "/api/v1/register"

mysql:
  username: "root"
  password: "root123456"
  database: "gin"
