package initialize

import (
	"learn-gin/core"
	"learn-gin/global"
	"learn-gin/model/system"
)

func InitDb() {
	global.DB = core.Db()

	err := global.DB.AutoMigrate(
		// 系统模块表
		system.Dept{},
		system.Menu{},
		system.MenuPermission{},
		system.Permission{},
		system.Role{},
		system.RolePermission{},
		system.User{},
		system.UserRole{},
		// 自动化模块表
		// Code generated by github.com/flipped-aurora/gin-vue-admin/server Begin; DO NOT EDIT.

		// Code generated by github.com/flipped-aurora/gin-vue-admin/server End; DO NOT EDIT.
	)
	if err != nil {
		panic(err)
	}
}
